Changes to support SC mode cluster
aerospike/aerospike-management-lib pull request #18
Opened 2022-11-09 06:54 UTC by sud82

2022-12-29 21:09 UTC, abhishekdwivedi3060 requested changes

2022-12-29 21:09 UTC, abhishekdwivedi3060 commented on deployment/strong_consistency.go
> +	return runRecluster(clHosts)
Can we add a check here to run `runRecluster` only when atleast one of the namespace's roster is actually set when diff found. Skip it when roster was same for all ns across all nodes

2022-12-30 10:31 UTC, tanmayja commented on deployment/strong_consistency.go
> +	log.Info("Check if we need to Get and set roster for SC namespaces")
nit pick: either make "get and set" or "Get and Set"

2022-12-30 10:31 UTC, tanmayja commented on deployment/strong_consistency.go
> +func recluster(clHost *host) error {
can we use this recluster function in other places, where recluster command is already being called.

2022-12-30 10:31 UTC, tanmayja commented on deployment/strong_consistency.go
> +func isNodeInRoster(clHost *host, ns string) (bool, error) {
ARE we using this function anywhere?

2023-01-02 07:41 UTC, sud82 commented on deployment/strong_consistency.go
> +func isNodeInRoster(clHost *host, ns string) (bool, error) {
Removed

2023-01-02 08:16 UTC, sud82 commented on deployment/strong_consistency.go
> +func recluster(clHost *host) error {
Right now these two recluster call implementations are a bit different. I feel that some older functions need rework. I will try to do that reformatting in a different commit.

2023-01-03 11:38 UTC, abhishekdwivedi3060 approved these changes

2023-01-10 07:40 UTC, merged