KO-169: Fixed go-lint issues
aerospike/aerospike-management-lib pull request #22
Opened 2023-02-02 11:54 UTC by abhishekdwivedi3060

TODO: Fix cyclomatic complexity

2023-02-13 05:29 UTC, tanmayja approved these changes

2023-02-20 13:32 UTC, sud82 requested changes

2023-02-20 13:32 UTC, sud82 commented on asconfig/constants.go
> +
use of const and string is inconsistent in a few files. In some places, const is used and in some places, the string is used. See if this can be made more consistent. 
Can we prepend `const` or `str` in the const to make their meaning more obvious?

2023-02-20 13:32 UTC, sud82 commented on deployment/cluster.go
> +const trueString = "true"
We start errors with `Err`. We can start strings with `str` or `string`

2023-02-20 13:32 UTC, sud82 commented on info/as_parser.go
> +	stat, configs, metadata, latency, throughput,
latency and throughput var used here will have `:` at the end but it was not there earlier. Check in the other places as well.

2023-02-20 13:32 UTC, sud82 commented on info/as_parser.go
> +	serviceMap := m.GetInnerVal(stat, "service")
Use const consistently

2023-02-20 13:32 UTC, sud82 commented on info/as_parser.go
> +	DefaultTimeout = 2 * time.Second
We can add prefix as `infoCmd` or `cmd` in the info commands const and `infoSection` or `section` in the info sections. At the top level, we have sections for eg (metadata and latency). Info commands are like `"get-config:context=network"`

2023-02-20 14:08 UTC, abhishekdwivedi3060 commented on info/test/parser_test.go
> +	err := os.WriteFile(filename, buf.Bytes(), 0o600)
The file created by this is not used anywhere and hence extra permission lint issue.
Actually, the func itself is not used anywhere but kept it as per discussion.

2023-02-21 05:24 UTC, abhishekdwivedi3060 commented on asconfig/constants.go
> +
Updated all the config related fields with a `key` prefix

2023-02-21 06:34 UTC, abhishekdwivedi3060 commented on info/as_parser.go
> +	DefaultTimeout = 2 * time.Second
Used :
const prefix-> for explicit constants
cmd prefix -> for command constants
key prefix -> for AS config keys

2023-02-22 06:35 UTC, sud82 requested changes

2023-02-22 06:35 UTC, sud82 commented on asconfig/conffilewriter.go
> +	delete(conf, name)
delete(conf, name) should be delete(conf, keyName).
Change "name" to keyName in line 136.
There are many places where "name" is still in use. Let's replace them, check that for other const as well.

2023-02-22 06:35 UTC, sud82 commented on info/as_parser.go
> +
Some of the const are commands. Crosscheck the commands from here https://docs.aerospike.com/reference/info

2023-02-22 06:54 UTC, abhishekdwivedi3060 commented on asconfig/conffilewriter.go
> +	delete(conf, name)
Not sure why golanci-lint is not throwing error for other occurrences of "name" string. Updated with const

2023-02-22 13:34 UTC, merged