Don't shadow sep in IsListField
aerospike/aerospike-management-lib pull request #23
Opened 2023-03-02 00:52 UTC by dwelch-spike

Return value "sep" was shadowing global variable "sep" leading to baseKey() always getting an empty separator.

This was causing `List found in non list field%!(EXTRA string=key, string=mounts)` when converting from yaml to asconf.

2023-03-02 07:44 UTC, abhishekdwivedi3060 reviewed
@dwelch-spike Thanks for finding this. Can you please fix go-lint issue?

2023-03-02 18:00 UTC, dwelch-spike commented
@abhishekdwivedi3060 fixed the linting issues

2023-03-03 11:47 UTC, abhishekdwivedi3060 requested changes

2023-03-03 11:47 UTC, abhishekdwivedi3060 commented on asconfig/utils.go
> +func isListField(key string) (exists bool, separater string) {
nit: 
```suggestion
func isListField(key string) (exists bool, separator string) {
```

2023-03-05 17:06 UTC, abhishekdwivedi3060 approved these changes

2023-03-06 05:54 UTC, sud82 approved these changes

2023-03-06 05:55 UTC, merged