TOOLS-2456 Parse asconfig.
aerospike/aerospike-management-lib pull request #27
Opened 2023-06-12 16:42 UTC by dwelch-spike

This PR exposes the asconfig parsing code in the management lib and fixes bugs found while adding the asconfig to yaml feature to [asconfig](https://github.com/aerospike/asconfig/pull/9).

2023-06-27 11:11 UTC, abhishekdwivedi3060 approved these changes

2023-07-10 16:45 UTC, dwelch-spike commented
@abhishekdwivedi3060 Will you merge this or should I?

2023-07-10 17:04 UTC, abhishekdwivedi3060 commented
> @abhishekdwivedi3060 Will you merge this or should I?

@sud82 Will merge this.

2023-07-17 12:21 UTC, sud82 requested changes

2023-07-20 15:35 UTC, dwelch-spike commented on asconfig/singular_plural.go
> +	"tls-authenticate-client":      "tls-authenticate-client",
This was causing issues because `tls-authenticate-clients` is not in the schemas but `tls-authenticate-client` is. https://github.com/aerospike/schemas/blob/dcf2b45bc6cac83ee859a7695ce9a239648834e5/json/aerospike/6.3.0.json#L894C39-L894C39

2023-07-20 16:03 UTC, dwelch-spike commented on asconfig/conffilewriter.go
> -
This doesn't work for the `run-as-daemon` config item because it accepts an argument. Treating the special bool fields as normal fields fixes this but I think it causes another problem where values of `false` aren't correctly written.

I think a better solution is to treat `run-as-daemon` as a special case. I'll work on that

2023-07-20 23:44 UTC, dwelch-spike commented on asconfig/conffilereader.go
> +func parseValue(k string, val interface{}) interface{} {
This code is copied from `ToParsedValues()` which used to be used here. I think it should be changed to support uint though, I'll work on that.

2023-07-20 23:58 UTC, dwelch-spike commented on asconfig/conffilereader.go
> +		if listSep == "" {
`tls-node` for example, falls into the default case of `isListField` returning an empty "" separator, the code on line 163 joins all the parsed tokens with their separator so without this case `tls-node  127.0.0.1 tls-name 4000` is parsed as `127.0.0.1tls-name4000`.

2023-07-21 00:02 UTC, dwelch-spike commented on asconfig/utils.go
> +		"enable-benchmarks-udf-sub", "enable-benchmarks-storage",
changed

2023-07-21 00:04 UTC, dwelch-spike commented on asconfig/utils.go
> +// TODO derive these from the schema file
it is possible, but I'd have to tie the parsing code (isStringField) to the schemas and aerospike version. Right now version and schemas are only used in validation and not required for parsing yaml or .conf. I'll think about this and will update these manually if I have to.

2023-07-21 00:04 UTC, dwelch-spike commented on asconfig/conffilereader.go
> +		lastToken := tok[len(tok)-1]
changed

2023-07-21 00:08 UTC, dwelch-spike commented on asconfig/utils.go
> +			name, ok = v[keyType].(string)
reverted this, "type" is a reserved word

2023-07-21 17:41 UTC, dwelch-spike commented on asconfig/conffilewriter.go
> -
done

2023-07-21 17:41 UTC, dwelch-spike commented on asconfig/conffilereader.go
> +func parseValue(k string, val interface{}) interface{} {
done

2023-07-26 09:40 UTC, abhishekdwivedi3060 commented on asconfig/singular_plural.go
> +	"tls-authenticate-client":      "tls-authenticate-client",
@dwelch-spike As per comment added by @sud82, `report-data-op` should be changed to plural. So to keep it consistent shouldn't all new fields added like `report-data-op-user` be changed to plural as well.
This change will require fixing these fields in Schema first

2023-08-17 11:42 UTC, sud82 requested changes

2023-08-22 17:25 UTC, dwelch-spike commented on asconfig/utils.go
> +func isSpecialOrNormalBoolField(key string) bool {
This identifies boolean fields that can act normally e.g. `run-as-daemon false` or act as a "special" boolean field where its mere presence implies a value e.g. `run-as-daemon`.

`run-as-daemon` is the only field I can find that behaves this way, see the server code https://github.com/citrusleaf/aerospike-server/blob/d5db3e1fba02010dea6614514fee685110f6d4c4/as/src/base/cfg.c#L2202

I think the function name matches the behavior. Please provide more details or a suggestion so I can make a change.

2023-08-22 20:10 UTC, dwelch-spike commented
I added updates needed to parse server 6.4 configurations. I wasn’t sure how to add secrets-address-port since it is delimited like list fields but is not part of a list section. I ended up calling it a "delimitedStringField" and parsing it as colon separated e.g. `secrets-address-port: 127.0.0.1:3004`.

2023-08-22 20:12 UTC, dwelch-spike commented
@sud82 I'm not sure if anything else needs to be done to get this merged. Please let me know if you are waiting for me to do anything. Thanks for the reviews!

2023-08-29 09:29 UTC, sud82 commented on asconfig/utils.go
> +func isSpecialOrNormalBoolField(key string) bool {
How about `isSpecialAndNormalBoolField`? `run-as-daemon` is normal as well as special.

2023-08-29 09:57 UTC, sud82 commented
@dwelch-spike, this can be merged. You pushed a few commits recently so I wasn't sure if you are done.

2023-08-29 16:33 UTC, dwelch-spike commented
@sud82 Awesome, thanks. I'm going to squash merge it.

2023-08-29 18:36 UTC, sud82 approved these changes

2023-08-29 22:40 UTC, merged