Tools 2749 generate config
aerospike/aerospike-management-lib pull request #39
Opened 2023-12-04 18:25 UTC by jdogmcsteezy

When making changes to existing API's, I checked the operator repo for any references. Let me know if I missed anything that might cause breaking changes on your end.

- Added a `GenerateConf()` method as part of the asconfig package. This required some updates to `as_parser.go` and `schemas.go`
- Added an option in `GenerateConf()` to remove all default values. This should reduce the size of the map only to include necessary fields. This relies on the schemas having the correct default values, which will need some updates, as I have identified here https://github.com/aerospike/schemas/issues/2.
- Added tests for as_parser.go. These tests only check the "config" output.
- Added tests for generate.go.
- Added some minimal tests for asconfig.go ToMap and GetFlatMap. I used these to help me understand the internal map formats.
- Added a unittest workflow with codecov integration

2023-12-05 01:30 UTC, jdogmcsteezy commented
I am going to add some integration tests

2023-12-11 23:28 UTC, dwelch-spike requested changes
Nice work! This will be super useful in asconfig. See comments below.

2023-12-11 23:28 UTC, dwelch-spike commented on info/as_parser.go
> +// }
Can this be removed?

2023-12-11 23:28 UTC, dwelch-spike commented on utils.go
> +}
Suggestion: You could add a compareVersions helper that takes a minLen argument then wrap that function to make the public CompareVersionsIgnoreRevision and CompareVersions. That would reduce duplicated logic.

2023-12-13 17:44 UTC, jdogmcsteezy commented on .github/workflows/tests.yml
> +      - main
I am going to change it to run on each commit. I was attempting to remove duplicate runs when you commit to an already open PR

2023-12-13 17:48 UTC, jdogmcsteezy commented on asconfig/generate.go
> +			flatConfig[key] = rackID
No, the effective replication factor is what you have, and the replication factor is what you want. Normally, the effective is lower in an unstable cluster. Also, Kevin described the situation where the customer sets the replication factor to 256 to allow the cluster to auto-adjust the effective replication factor as nodes are added and removed.

2023-12-13 17:49 UTC, jdogmcsteezy commented on asconfig/generate.go
> +type renameKeysStep struct {
The reason is that I want it to be used in the future if other non-logging keys need to be changed. I don't want more steps to be added than are needed

2023-12-13 17:51 UTC, jdogmcsteezy commented on asconfig/generate.go
> +}
good catch

2023-12-13 17:52 UTC, jdogmcsteezy commented on asconfig/generate.go
> +// new key, the index, and the value as a string. If the key is not indexed or the value is
Good catch. It used to

2023-12-13 17:54 UTC, jdogmcsteezy commented on asconfig/generate.go
> +					value = strings.Split(strVal, ",")
Yes, isListField will return false for LDAP fields. As far as I know ',' is constant

2023-12-13 18:59 UTC, jdogmcsteezy commented on asconfig/generate.go
> +			}
yes its the same

2023-12-13 19:00 UTC, jdogmcsteezy commented on asconfig/generate.go
> +	}
The sever does not report the `any`. The best way to remove the defaults and reduce the size of this section is to find out which section can best be replaced with `any`.

Normally a user will have something like `context any INFO` but the server just spits back every context with level INFO. this is trying to fix that issue

2023-12-13 19:29 UTC, jdogmcsteezy commented on asconfig/generate.go
> +		}
No, remember that this is a flat map so currently all the config keys are in the format `security.enable-quotas`. This added step simply ensures an empty security context is there if all other security keys are deleted. It is a quirk of the expandConf method. In this case all security keys might be set to the default in which case they are all removed. expandConf will not insert an empty security context unless you explicitly tell it to

2023-12-13 19:49 UTC, jdogmcsteezy commented on asconfig/utils.go
> +	baseKey := baseKey(key)
if the key is `namespace.{test}.index-type` baseKey returns `index-type`

2023-12-13 19:56 UTC, jdogmcsteezy commented on utils.go
> +}
This is just me moving two functions to a more accessible location

2023-12-15 11:24 UTC, abhishekdwivedi3060 requested changes

2023-12-15 11:29 UTC, abhishekdwivedi3060 reviewed
There are some files at the root of the repo like `parser.go`, `stats.go`, `utils.go`.
Can we think of restructuring the code and move them to a dedicated pkg ?
May be in this PR or can be done separately to limit the scope of this PR.

2023-12-15 17:51 UTC, jdogmcsteezy commented on .golangci.yml
> +    - path: '(.+)test\.go'
Normally, I consider that standards are different test code and might not always follow the best practices of the code they are testing. Maybe a flat-out exclusion for all linters is not the way to go here. Or maybe I should remove the test code exclusion altogether.  

I'll look into removing this exclusion and see if I can come up with any objections

2023-12-15 17:53 UTC, jdogmcsteezy commented on .github/workflows/golangci-lint.yaml
> +          go install github.com/golang/mock/mockgen@v1.6.0
golang archived their own tool! 

Will do

2023-12-15 20:15 UTC, jdogmcsteezy commented on asconfig/schema.go
> +	removedKeys := map[string]bool{}
I am not sure what `set` implementation you are talking about but I changed it to `struct{}`

2023-12-15 20:22 UTC, jdogmcsteezy commented on asconfig/schema.go
> +	removedKeys := map[string]bool{}
TDIL `struct{}` doesn't consume any space

2023-12-15 21:12 UTC, jdogmcsteezy commented on info/as_parser.go
> +func (f *aerospikeConnFactory) NewConnection(
I decided to make the `Connection interface` and `ConnectionFactory interface` public. `aerospikeConnFactory.NewConnection` is public to implement the `ConnectionFactory interface`. I did not want `aerospikeConnFactory` to be public because it is the default. Let me know if you oppose this decision

2023-12-15 21:13 UTC, jdogmcsteezy commented on info/as_parser.go
> +		// 	rawCmdList = append(rawCmdList, cmds...)
Oof, good catch. I think that was something I did while using a debugger

2023-12-15 21:49 UTC, jdogmcsteezy commented on info/as_parser.go
> +			m = mergeDicts(m, resp)
also good catch

2023-12-15 21:54 UTC, jdogmcsteezy commented on asconfig/generate.go
> +			log.V(-1).Info("Unexpected type when comparing default (%s) to config value (%s)", val, confVal)
Yes, forgive me. I should have payed more attention to how they are used

2023-12-15 21:55 UTC, jdogmcsteezy commented on asconfig/generate.go
> +	conf["config"] = configs
works for me

2023-12-15 22:25 UTC, jdogmcsteezy commented on asconfig/generate.go
> +		conf["racks"] = configs["racks"]
To do so I had to make constants in the info package public. I hope that is ok. Otherwise, I can create constants in the asconfig package

2023-12-15 22:28 UTC, jdogmcsteezy commented on info/as_parser.go
> +			m = mergeDicts(m, resp)
Decided to wrap it with a Lock

2023-12-15 22:30 UTC, jdogmcsteezy commented
> There are some files at the root of the repo like `parser.go`, `stats.go`, `utils.go`. Can we think of restructuring the code and move them to a dedicated pkg ? May be in this PR or can be done separately to limit the scope of this PR.

I would prefer to limit the scope. Also, I am not sure I would be the best one to re-organize because I am not sure how they are consumed

2023-12-19 16:28 UTC, jdogmcsteezy commented
I am not yet authorized to view the snyk Aerospike Operator project to see what is causing the failtures

2023-12-20 08:44 UTC, abhishekdwivedi3060 approved these changes

2023-12-20 08:44 UTC, abhishekdwivedi3060 commented on test/containers.go
> +	}
This part can be moved out to a func for reusing in both `RunAerospikeContainer` and `RestartAerospikeContainer` funcs

2023-12-21 18:18 UTC, dwelch-spike commented on asconfig/generate.go
> +			flatConfig[key] = rackID
But if we are capturing the configuration? Wouldn't you want to preserve what the user configured (replication factor)? That way if you generate a config from this data, it will set the replication factor to what they originally configured.

2023-12-21 18:38 UTC, jdogmcsteezy commented on asconfig/generate.go
> +			flatConfig[key] = rackID
These two sentences are contradictory. To me "originally configured" means what is in the aerospike.conf file. This does set the replication-factor to what they originally configured

2023-12-21 18:43 UTC, dwelch-spike commented on asconfig/generate.go
> +			flatConfig[key] = rackID
I miss understood this when I gave it another look. I thought replication factor was being replaced.

2023-12-21 18:43 UTC, dwelch-spike approved these changes
LGTM

2023-12-29 13:30 UTC, merged