Adding functions to support dynamically change Aerospikeconfig
aerospike/aerospike-management-lib pull request #40
Opened 2023-12-08 10:52 UTC by tanmayja

2024-02-07 16:59 UTC, abhishekdwivedi3060 requested changes
Write func comments/descriptions wherever missing

2024-02-07 16:59 UTC, abhishekdwivedi3060 commented on asconfig/utils.go
> +				operationValueMap := make(map[string]interface{})
we are populating the `operationValueMap` map inside `handleSliceFields` func and not using it later. So there is no  need to define it here. Better to create and use it inside the `handleSliceFields` func

2024-02-07 16:59 UTC, abhishekdwivedi3060 commented on asconfig/utils.go
> +			operationValueMap := make(map[string]interface{})
Same applies here

2024-02-07 16:59 UTC, abhishekdwivedi3060 commented on asconfig/utils.go
> +		statusSet := sets.NewSet[string]()
I think we should not use status or spec related vars here. Use desired/current vars instead

2024-02-13 14:17 UTC, abhishekdwivedi3060 requested changes

2024-02-13 14:19 UTC, tanmayja commented on asconfig/as_setconfig.go
> +	logs             = "logs"
already done in my local repo.

2024-03-26 12:35 UTC, abhishekdwivedi3060 approved these changes

2024-04-03 17:38 UTC, sud82 requested changes

2024-04-04 05:24 UTC, tanmayja commented on asconfig/upgrade.go
> +package asconfig
As we import deployment in as_setconfig.go, and this file import asconfig for some functions, leads to import cycles. To avoid import cycles, I moved it to asconfig because it does not have any dependency on deployment package.

2024-04-04 05:28 UTC, tanmayja commented on info/as_parser.go
> +	xdrConfigMap := ParseIntoMap(rawMap[cmd], ";", "=")
yeah, there was a bug related to strings.Split, as it returns the array of size 1 even if input string is "".

2024-04-04 06:15 UTC, tanmayja commented on asconfig/as_getconfig.go
> +			logger.Info("Config is nil", "path", strings.Join(tokens[:idx+2], sep))
To print the exact path to which config is null. Eg. Path is "xdc.dcs.{dc1}.namespaces.{ns1}.xyz". If dc1 does not exist, this logger will only print` "Config is nil path xdc.dcs.{dc1}"` instead of full path.

2024-04-05 07:32 UTC, sud82 commented on deployment/cluster.go
> +	log := c.log.WithValues("nodes", getHostIDsFromHostConns(hosts))
"nodes" are also added in the setConfigCommandsOnHosts function. It can be removed from here.

2024-04-05 07:42 UTC, sud82 approved these changes

2024-04-05 07:50 UTC, merged