fix: Fix existing test cases
aerospike/aerospike-management-lib pull request #56
Opened 2024-09-11 07:25 UTC by a-spiker

Fixing the existing test cases

2024-09-11 17:59 UTC, dwelch-spike commented on info/as_parser.go
> -		xdrConfigMap[ConfigDCContext] = struct{}{}
Why change this? Does it cause a bug somewhere else?

2024-09-11 20:33 UTC, dwelch-spike commented
@a-spiker For our understanding could you lay out why these changes were made? What issues were they causing?

1. "null" changed to ""
2. struct{}{} -> make(lib.Stats)

2024-09-12 02:11 UTC, jdogmcsteezy requested changes

2024-09-12 02:11 UTC, jdogmcsteezy commented on asconfig/generate_test.go
> -				"storage-engine.encryption-old-key-file":    "null",
Rather than editing the input config, which you are doing here, I think you should edit the output config. [Here](https://github.com/aerospike/aerospike-management-lib/blob/master/asconfig/generate.go#L574-L576) is section of code that removes "null" values from the output config. The "null" value is returned from the server and the goal of this code is to turn it into a map struct (lib.Stats) that can be easily marshalled to a yaml file.

Basically, what I think you should do is remove `key-file`, `old-key-file`, etc. from the expected array rather than change what the server response looks like

2024-09-12 06:25 UTC, a-spiker commented
> @a-spiker For our understanding could you lay out why these changes were made? What issues were they causing?
> 

> 2. struct{}{} -> make(lib.Stats)

struct{}{} -> make(lib.Stats)
There is an existing  test case which was failing, which expects dis to be of lib.Stats. Ideally all the sub configs should be instance of lib.Stats for consistent parsing..   It was changed here https://github.com/aerospike/aerospike-management-lib/pull/40/files#diff-3e8a272f186a1070104d40c5f775480b3f913489b147098e3662f7eda1cf8f1cR1149 . if the dc values is empty it was still going to have Len > 0 for the split. 


> 1. "null" changed to ""
As per the review, I have changed the expected values rather than test generated values.

2024-09-12 16:19 UTC, jdogmcsteezy approved these changes

2024-09-12 16:33 UTC, tanmayja commented on info/as_parser.go
> +		xdrConfigMap[ConfigDCContext] = make(lib.Stats)
should we make the same change at line 1173?

2024-09-12 22:25 UTC, dwelch-spike approved these changes
LGTM

2024-09-13 04:45 UTC, tanmayja approved these changes

2024-09-13 04:45 UTC, merged