fixing dc and xdr stat collection [TOOLS-3056]
aerospike/aerospike-management-lib pull request #63
Opened 2024-11-06 11:21 UTC by tanmayja

Changes included in this PR:

1. Fix XDR and DC stat collections.
2. bins/<namespace name> command is removed from 7.0.
3. Removing server version pre5 support.
4. Remove throughput command.
5. Fix generate command panic for community edition.
6. Providing wrapper functions to set configs in aerospike cluster.

2024-11-28 07:29 UTC, a-spiker commented on asconfig/as_getconfig.go
>  	asinfo := info.NewAsInfo(conn.Log, &h, aerospikePolicy)
Kindly close the connection opened by the client, there is a connection leak

2025-06-06 08:07 UTC, a-spiker commented on asconfig/as_getconfig.go
> +			conn.Log.Info("Config is nil", "context", ctxConf)
```
confToReturn[path] = nil
continue
```

should we continue to process other paths or stop here?

2025-06-06 08:15 UTC, a-spiker commented on info/as_parser.go
> +	if !ok || rawNames == "" {
if not ok , which means parsing failure. should we log this ... else error will be silently dropped with empty string

2025-06-06 08:22 UTC, a-spiker commented on asconfig/as_setconfig.go
> +		valueMap := make(map[OpType]interface{})
can we use sync pool outside the loop

valueMapPool := sync.Pool{
    New: func() interface{} {
        return make(map[OpType]interface{})
    },
}

2025-06-06 08:23 UTC, a-spiker requested changes
requested minor reviews

2025-06-09 05:15 UTC, a-spiker commented on asconfig/as_getconfig.go
> +			conn.Log.Info("Config is nil", "context", ctxConf)
Resolved after discussion , currently we are not returning partial success.

2025-06-09 05:15 UTC, a-spiker commented on info/as_parser.go
> +	if !ok || rawNames == "" {
Resolved after discussion, as we are not logging parsing problems under the current scope.

2025-06-09 05:16 UTC, a-spiker commented on asconfig/as_setconfig.go
> +		valueMap := make(map[OpType]interface{})
currently we cannot resuse the maps as they are all forming the config tree.

2025-06-26 11:58 UTC, abhishekdwivedi3060 requested changes

2025-06-26 11:58 UTC, abhishekdwivedi3060 commented on info/as_parser.go
> +			ConfigNamespaceNames, ConfigLogIDs,
Seems like ConfigDCContext, ConfigDCNames, ConfigNamespaceNames, ConfigLogIDs are unused.
Please confirm the use and remove them

2025-06-26 11:58 UTC, abhishekdwivedi3060 commented on info/as_parser.go
> -	statMap["xdr"] = parseBasicInfo(rawMap[constStatXDR])
Q: Will this removal cause any backward incompatibility? meaning is there a need to populate the `xdr` stats with `cmdConfigXDR` cmd or removing completely is fine?

2025-06-27 06:32 UTC, abhishekdwivedi3060 approved these changes

2025-07-09 07:13 UTC, a-spiker approved these changes
LGTM

2025-07-09 12:06 UTC, merged